services:
  identity-resolver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - OBJECT_STORAGE_ENDPOINT=minio
      - OBJECT_STORAGE_PORT=9000
      - OBJECT_STORAGE_USE_SSL=false
      - OBJECT_STORAGE_ACCESS_KEY=minioadmin
      - OBJECT_STORAGE_SECRET_KEY=minioadmin
      - OBJECT_STORAGE_BUCKET_NAME=idr-bucket
      - IDENTIFIER_PATH=identifiers
      - OBJECT_STORAGE_PATH_STYLE=true
      - API_KEY=test123
      - RESOLVER_DOMAIN=http://localhost:3000/api/1.0.0
      - APP_NAME=IDR
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - minio

  minio:
    hostname: minio
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z-cpuv1
    command: server /data --console-address ":9090"
    ports:
      - '9000:9000'
      - '9090:9090'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

    environment:
      - OBJECT_STORAGE_ROOT_USER=minioadmin
      - OBJECT_STORAGE_ROOT_PASSWORD=minioadmin

    volumes:
      - ${OBJECT_STORAGE_DATA_DIR:-./object_storage_data}:/data
